algoritmo "ParOUImpar"
var
   Num: Inteiro
inicio
      Escreval ("------------------------------------------")
      Escreval ("           Numero Par ou Impar            ")
      Escreval ("------------------------------------------")
      
      Escreva ("Digite um numero inteiro: ")
      Leia (Num)
      
      Se (Num % 2 = 0) Entao
      Escreva ("O numero ", Num, " e par")
      Senao
           Escreva ("O numero ", Num, " e impar")

           FimSe

fimalgoritmo
