algoritmo "semnome"
var
M, Km, Hm, Dam, Dm, Cm, Mm: Real
inicio
Escreva ("Digite a distancia em metros: ")
Leia (M)

Km <- M / 1000

Hm <- M / 100

Dam <- M / 10

Dm <- M * 10

Cm <- M * 100

Mm <- M * 1000

Escreval ("A distancia de ", M, " M corresponde a: ")

Escreval (Km, "Km")

Escreval (Hm, "Hm")

Escreval (Dam, "Dam")

Escreval (Dm, "Dm")

Escreval (Cm, "Cm")

Escreva (Mm, "Mm")

fimalgoritmo